name: 📚 Documentation Issue
description: Report an issue with documentation or request documentation improvements
title: "[DOCS] "
labels: ["documentation", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation! Please describe the documentation issue or improvement needed.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is this about?
      options:
        - README files
        - API Documentation
        - MCP Tool Documentation
        - Development Setup Guide
        - Deployment Guide
        - Testing Documentation
        - Architecture Documentation
        - Code Comments
        - GitHub Templates
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear/confusing explanation
        - Broken links
        - Formatting issues
        - Typos/grammar
        - Missing examples
        - Needs more detail
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: |
        Where is this documentation located? Please provide:
        - File path (e.g., `/README.md`, `/docs/api.md`)
        - URL (if applicable)
        - Section name or heading
      placeholder: |
        File: /path/to/file.md
        Section: "Getting Started"
        Line: 42
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the documentation issue in detail.
      placeholder: What's wrong with the current documentation?
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: |
        If you have suggestions for how to fix or improve this documentation, please share them.
        You can include:
        - Corrected text
        - Additional examples
        - Better explanations
        - Links to helpful resources

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Any additional context that might be helpful:
        - Who is the target audience?
        - What use case prompted this?
        - Any related issues or discussions?

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked that this documentation issue still exists
          required: true
        - label: I would be willing to help fix this documentation
          required: false
