name: Authentication Security Validation

on:
  pull_request:
    branches: [main]
    paths:
      - "FabrikamApi/src/**"
      - "FabrikamMcp/src/**"
      - "FabrikamContracts/**"
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Security Analysis

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore Fabrikam.sln

      - name: Build solution
        run: dotnet build Fabrikam.sln --no-restore --configuration Release

      - name: Run security tests
        run: |
          dotnet test FabrikamTests/ --filter "Category=Security" --logger trx --results-directory TestResults/

      - name: Authentication Integration Tests
        run: |
          dotnet test FabrikamTests/ --filter "Category=Authentication" --logger trx --results-directory TestResults/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-test-results
          path: TestResults/

  dependency-scan:
    runs-on: ubuntu-latest
    name: Dependency Security Scan

    steps:
      - uses: actions/checkout@v4

      - name: Run dependency security scan
        run: |
          # Alternative to Snyk - use built-in dotnet security scanning
          dotnet list package --vulnerable --include-transitive
          dotnet list package --deprecated

  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality Analysis

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Run static analysis
        run: |
          dotnet format --verify-no-changes --verbosity diagnostic
          dotnet build Fabrikam.sln --configuration Release --verbosity minimal
