# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - fabrikam-mcp-dev-izbD

on:
  push:
    branches:
      - main
    paths:
      - 'FabrikamMcp/**'
      - '.github/workflows/main_fabrikam-mcp-dev-izbd.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build FabrikamMcp/src/FabrikamMcp.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish FabrikamMcp/src/FabrikamMcp.csproj -c Release -o ./publish

      - name: Verify build output
        run: |
          echo "Build output contents:"
          ls -la ./publish/
          echo "Looking for .runtimeconfig.json files:"
          find ./publish/ -name "*.runtimeconfig.json" || echo "No .runtimeconfig.json files found"
          echo "Looking for main DLL:"
          find ./publish/ -name "FabrikamMcp.dll" || echo "FabrikamMcp.dll not found"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app-mcp
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app-mcp
          
      - name: Verify deployment package
        run: |
          echo "Contents of deployment package:"
          ls -la
          echo "Runtime config files:"
          find . -name "*.runtimeconfig.json" -type f || echo "No runtime config files found"
          echo "DLL files:"
          find . -name "*.dll" -type f || echo "No DLL files found"
          echo "Main application DLL:"
          find . -name "FabrikamMcp.dll" -type f || echo "FabrikamMcp.dll not found"
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A8C8EF1B326A471D88D0808AB703A5EE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9C449FA4736D46E6A0CFD35DC61B177A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B4519DE6CF4C4656B779761582012720 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fabrikam-mcp-dev-izbD'
          slot-name: 'Production'
          package: .
          
      - name: Set startup command
        continue-on-error: true
        run: |
          echo "Setting startup command..."
          az webapp config set --resource-group rg-fabrikam-dev-izbd --name fabrikam-mcp-dev-izbD --startup-file "dotnet FabrikamMcp.dll" || echo "Warning: Could not set startup command"
          
          echo "Restarting app to apply startup command..."
          az webapp restart --resource-group rg-fabrikam-dev-izbd --name fabrikam-mcp-dev-izbD || echo "Warning: Could not restart app"
          
      - name: Health Check
        continue-on-error: true
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          
          echo "Testing MCP status endpoint..."
          echo "Trying to reach: https://fabrikam-mcp-dev-izbd.azurewebsites.net/status"
          
          for i in {1..5}; do
            echo "Health check attempt $i..."
            if curl -f -s https://fabrikam-mcp-dev-izbd.azurewebsites.net/status; then
              echo "✅ MCP status endpoint is responding!"
              exit 0
            else
              echo "⏳ Status endpoint failed, waiting 30 seconds before retry..."
              sleep 30
            fi
          done
          
          echo "⚠️ Health check failed after 5 attempts, but deployment may still be successful"
          echo "Check the Azure portal for deployment status"
          
      - name: Deployment Summary
        run: |
          echo "🚀 MCP Deployment process completed!"
          echo "📊 Deployment Summary:"
          echo "  ✅ Build: Successful"
          echo "  ✅ Publish: Successful" 
          echo "  ✅ Deploy: Successful"
          echo "  ℹ️  Health Check: See previous step"
          echo ""
          echo "🌐 MCP Server URL: https://fabrikam-mcp-dev-izbd.azurewebsites.net"
          echo "🔍 Status Endpoint: https://fabrikam-mcp-dev-izbd.azurewebsites.net/status"
          echo ""
          echo "If health checks failed, the app may still be starting up."
          echo "Check the Azure portal for final deployment status."
          
          echo "MCP deployment completed successfully!"
          