name: Testing Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Run All Tests
      run: dotnet test FabrikamTests/FabrikamTests.csproj --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory TestResults
    
    - name: Test Summary
      run: |
        echo "Test execution completed. Check results above for any failures."
        if [ $? -eq 0 ]; then
          echo "✅ All tests passed!"
        else
          echo "❌ Some tests failed. Check the output above."
          exit 1
        fi

  api-contract-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Start API
      run: |
        cd FabrikamApi/src
        dotnet run --urls "http://localhost:5235" &
        sleep 10
    
    - name: Test API Contract
      run: |
        # Test critical endpoints
        curl -f http://localhost:5235/api/orders || exit 1
        curl -f http://localhost:5235/api/orders/analytics || exit 1
        curl -f http://localhost:5235/api/customers || exit 1
        curl -f http://localhost:5235/api/products || exit 1
        curl -f http://localhost:5235/api/supporttickets || exit 1
        curl -f http://localhost:5235/api/info || exit 1
    
    - name: Validate Analytics Response Structure
      run: |
        response=$(curl -s http://localhost:5235/api/orders/analytics)
        echo $response | jq -e '.summary' > /dev/null || exit 1
        echo $response | jq -e '.byStatus' > /dev/null || exit 1
        echo $response | jq -e '.byRegion' > /dev/null || exit 1
        echo $response | jq -e '.recentTrends' > /dev/null || exit 1
