name: Testing Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Run API Tests
      run: dotnet test FabrikamTests/FabrikamTests.csproj --no-build --verbosity normal --filter "Category=Api"
    
    - name: Run MCP Tests
      run: dotnet test FabrikamTests/FabrikamTests.csproj --no-build --verbosity normal --filter "Category=Mcp"
    
    - name: Run Integration Tests
      run: dotnet test FabrikamTests/FabrikamTests.csproj --no-build --verbosity normal --filter "Category=Integration"
    
    - name: Generate Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results
        path: '**/TestResults/*.xml'
        reporter: dotnet-trx

  api-contract-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Start API
      run: |
        cd FabrikamApi/src
        dotnet run --urls "http://localhost:5235" &
        sleep 10
    
    - name: Test API Contract
      run: |
        # Test critical endpoints
        curl -f http://localhost:5235/api/orders || exit 1
        curl -f http://localhost:5235/api/orders/analytics || exit 1
        curl -f http://localhost:5235/api/customers || exit 1
        curl -f http://localhost:5235/api/products || exit 1
        curl -f http://localhost:5235/api/support-tickets || exit 1
        curl -f http://localhost:5235/api/info || exit 1
    
    - name: Validate Analytics Response Structure
      run: |
        response=$(curl -s http://localhost:5235/api/orders/analytics)
        echo $response | jq -e '.summary' > /dev/null || exit 1
        echo $response | jq -e '.byStatus' > /dev/null || exit 1
        echo $response | jq -e '.byRegion' > /dev/null || exit 1
        echo $response | jq -e '.recentTrends' > /dev/null || exit 1
